### ISSUE TITLE
Hook execution error

### ISSUE THREAD

**Issue by RobertoMD** [rc9000/netdisco_discover_hook#1]
Hi,
I have set up netdisco in order to use discover_hook and remove uplinks on ip phones and APs:
- discover_hook in /home/netdisco/perl5 with 755 permissions
- this paragraph in deployment.yml:

```
hooks:
  - type: 'exec'
    event: 'discover'
    with:
      cmd: '/home/netdisco/perl5/bin/discover_hook [% ip %]'
discover_hook:
  no_uplink_port:
    # ip phones
    - remote_type: Cisco IP Phone
    - remote_type: cisco AIR
```
, I'm getting this error for the execution of the hook (got by selecting the admin table as proposed):

```
{"result":256,"timeout":0,"pid":56965,"stderr":"[56965] 2022-05-05 06:54:51 error Usage: /home/netdisco/perl5/bin/discover_hook <ip>\n","cmd":"/home/netdisco/perl5/bin/discover_hook ","stdout":""}
```

, so it looks like netdisco is not passing the IP of the device to the hook script. Do you know how to solve this issue? Thanks
